/**
 * FreshCart - Seed Data & Mock Database
 * Shared across all pages via <script src="../js/data.js"> or <script src="js/data.js">
 */

const INITIAL_CATEGORIES = [
  { id: "fruits", name: "Fruits", itemCount: 14, description: "Farm fresh organic fruits picked daily", image: "https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "vegetables", name: "Vegetables", itemCount: 18, description: "Crisp and fresh locally sourced veggies", image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "dairy", name: "Dairy & Eggs", itemCount: 12, description: "Fresh milk, paneer, curd, cheese and farm eggs", image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "bakery", name: "Bakery", itemCount: 10, description: "Artisanal breads, cookies, cakes & pastries", image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "meat-seafood", name: "Meat & Seafood", itemCount: 8, description: "Hygienically cleaned fresh cuts & sea fish", image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "snacks", name: "Snacks & Munchies", itemCount: 22, description: "Namkeens, chips, roasted nuts & healthy bites", image: "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "beverages", name: "Beverages", itemCount: 16, description: "Fresh cold juices, herbal tea, coffee & sodas", image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "rice-grains", name: "Rice & Grains", itemCount: 15, description: "Aromatic Basmati, millets, wheat flour & pulses", image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "cooking-essentials", name: "Cooking Essentials", itemCount: 20, description: "Cold-pressed oils, pure ghee, whole spices & salts", image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "frozen-foods", name: "Frozen Foods", itemCount: 9, description: "Ready to fry samosas, frozen peas, berries & desserts", image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "personal-care", name: "Personal Care", itemCount: 14, description: "Organic body wash, shampoos, soaps & oral care", image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80", status: "Active" },
  { id: "household", name: "Household", itemCount: 11, description: "Eco detergents, floor cleaners, wipes & trash bags", image: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=400&q=80", status: "Active" }
];

const INITIAL_PRODUCTS = [
  { id:"prod-1", name:"Fresh Shimla Red Apples", category:"fruits", brand:"FreshFarm Organics", sku:"FRT-APP-001", price:149, originalPrice:179, discount:17, unit:"1 kg", stock:45, minStock:10, rating:4.8, reviewsCount:128, image:"https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80", description:"Hand-picked crisp red Shimla apples known for their natural sweetness and rich antioxidant benefits. Directly sourced from Himalayan orchards.", tags:["Organic","Farm Fresh","Immunity"], status:"In Stock", featured:true, badge:"Popular" },
  { id:"prod-2", name:"Organic Robusta Bananas", category:"fruits", brand:"GreenField", sku:"FRT-BAN-002", price:49, originalPrice:65, discount:25, unit:"1 kg (approx 6-7 pcs)", stock:60, minStock:15, rating:4.6, reviewsCount:94, image:"https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80", description:"Naturally ripened Robusta bananas packed with dietary potassium, vitamins, and energy.", tags:["Naturally Ripened","Energy Rich"], status:"In Stock", featured:true, badge:"Best Value" },
  { id:"prod-3", name:"Alphonso Mangoes (Devgad)", category:"fruits", brand:"Ratnagiri Heritage", sku:"FRT-MNG-003", price:649, originalPrice:799, discount:19, unit:"1 Dozen (12 pcs)", stock:14, minStock:5, rating:4.9, reviewsCount:215, image:"https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80", description:"King of Mangoes sourced straight from GI-tagged coastal Devgad orchards. Unmatched aroma, saffron flesh and heavenly sweetness.", tags:["GI Tagged","Premium","Seasonal"], status:"In Stock", featured:true, badge:"Seasonal Deal" },
  { id:"prod-4", name:"Farm Fresh Hybrid Tomatoes", category:"vegetables", brand:"Local Roots", sku:"VEG-TOM-004", price:38, originalPrice:50, discount:24, unit:"1 kg", stock:80, minStock:20, rating:4.5, reviewsCount:82, image:"https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80", description:"Juicy, firm, and vibrant red hybrid tomatoes. Ideal for curries, salads and everyday Indian cooking.", tags:["Daily Essential","Locally Sourced"], status:"In Stock", featured:true, badge:"Hot Deal" },
  { id:"prod-5", name:"Baby Spinach Leaves (Palak)", category:"vegetables", brand:"HydroFresh", sku:"VEG-SPN-005", price:29, originalPrice:40, discount:28, unit:"250 g", stock:35, minStock:10, rating:4.7, reviewsCount:67, image:"https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80", description:"Hydroponically grown tender baby spinach, pesticide-free, pre-cleaned and ready to cook.", tags:["Pesticide Free","Pre-washed"], status:"In Stock", featured:false, badge:"28% OFF" },
  { id:"prod-6", name:"Fresh Red Onions", category:"vegetables", brand:"Nasik Agro", sku:"VEG-ONI-006", price:45, originalPrice:60, discount:25, unit:"1 kg", stock:120, minStock:25, rating:4.6, reviewsCount:154, image:"https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80", description:"Top grade pungent Nasik red onions. Crispy layers with rich culinary flavor.", tags:["Grade A","Kitchen Staple"], status:"In Stock", featured:true, badge:"Staple" },
  { id:"prod-7", name:"Organic Malai Paneer", category:"dairy", brand:"The Organic World", sku:"DAI-PAN-007", price:115, originalPrice:135, discount:15, unit:"200 g", stock:22, minStock:8, rating:4.9, reviewsCount:198, image:"https://theorganicworld.com/storage/app/public/product/thumbnail/2026-01-13-69663eb92b5f6.png", description:"Soft, spongy fresh organic cottage cheese made from 100% pure cow's milk with zero preservatives.", tags:["High Protein","No Preservatives","Organic"], status:"In Stock", featured:true, badge:"Top Rated" },
  { id:"prod-8", name:"Pure Cow Milk - Toned", category:"dairy", brand:"Amul Gold", sku:"DAI-MLK-008", price:66, originalPrice:72, discount:8, unit:"1 Litre Pouch", stock:55, minStock:15, rating:4.8, reviewsCount:310, image:"https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80", description:"Pasteurized and homogenized pure toned milk. Rich in calcium and essential vitamins.", tags:["Daily Fresh","Calcium"], status:"In Stock", featured:false, badge:null },
  { id:"prod-9", name:"Free Range Farm Brown Eggs", category:"dairy", brand:"Eggetarian Choice", sku:"DAI-EGG-009", price:89, originalPrice:110, discount:19, unit:"Pack of 6", stock:40, minStock:10, rating:4.7, reviewsCount:88, image:"https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&q=80", description:"Antibiotic-free, hormone-free brown eggs from free-roaming hens. Golden yolk with 6g natural protein per egg.", tags:["Cage Free","Antibiotic Free"], status:"In Stock", featured:true, badge:"19% OFF" },
  { id:"prod-10", name:"100% Whole Wheat Sourdough Bread", category:"bakery", brand:"The Artisanal Baker", sku:"BAK-BRD-010", price:95, originalPrice:120, discount:21, unit:"400 g Loaf", stock:18, minStock:6, rating:4.8, reviewsCount:52, image:"https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=600&q=80", description:"Slow-fermented artisan sourdough baked fresh every dawn using whole grain flour, sea salt and natural wild starter.", tags:["Zero Maida","Gut Friendly"], status:"In Stock", featured:false, badge:"Freshly Baked" },
  { id:"prod-11", name:"Butter Croissant (Pack of 2)", category:"bakery", brand:"French Oven", sku:"BAK-CRO-011", price:139, originalPrice:160, discount:13, unit:"2 pcs (150 g)", stock:12, minStock:5, rating:4.6, reviewsCount:39, image:"https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80", description:"Flaky, golden-brown French butter croissants with 27 delicate layers.", tags:["Pure Butter","European Recipe"], status:"In Stock", featured:false, badge:null },
  { id:"prod-12", name:"Fresh Boneless Chicken Breast", category:"meat-seafood", brand:"FreshCuts", sku:"MET-CHK-012", price:249, originalPrice:299, discount:17, unit:"500 g", stock:25, minStock:8, rating:4.9, reviewsCount:142, image:"https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=600&q=80", description:"Tender, succulent and chilled (never frozen) antibiotic-residue-free chicken breasts.", tags:["Chemical Free","High Protein"], status:"In Stock", featured:true, badge:"Best Seller" },
  { id:"prod-13", name:"Fresh Sea Prawns (Cleaned & Deveined)", category:"meat-seafood", brand:"Coastal Catch", sku:"MET-PRW-013", price:399, originalPrice:479, discount:17, unit:"400 g net", stock:8, minStock:6, rating:4.7, reviewsCount:76, image:"https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=600&q=80", description:"Medium-sized wild caught sea prawns, expertly cleaned and deveined.", tags:["Wild Caught","Ready to Cook"], status:"In Stock", featured:false, badge:"Low Stock" },
  { id:"prod-14", name:"Roasted California Almonds - Smoky Barbeque", category:"snacks", brand:"The Snack Company", sku:"SNK-ALM-014", price:185, originalPrice:220, discount:16, unit:"100 g", stock:38, minStock:12, rating:4.9, reviewsCount:187, image:"https://cdn01.pharmeasy.in/dam/products_otc/X38039/the-snack-company-roasted-california-almonds-smoky-barbeque-100g-roasted-not-fried-6.01-1786630468.jpg", description:"Slow dry-roasted California almonds tossed in authentic smoky barbeque seasoning. Roasted, never fried.", tags:["Heart Healthy","Gluten Free","Roasted Not Fried"], status:"In Stock", featured:true, badge:"25% OFF" },
  { id:"prod-15", name:"Baked Multigrain Tortilla Chips", category:"snacks", brand:"SnackRight", sku:"SNK-CHP-015", price:85, originalPrice:99, discount:14, unit:"150 g", stock:50, minStock:15, rating:4.4, reviewsCount:63, image:"https://m.media-amazon.com/images/I/71CLU1h-V+L._SX679_.jpg", description:"Oven-baked whole corn and quinoa tortilla chips infused with smoked jalapeño seasoning.", tags:["Baked Not Fried","Zero Cholesterol"], status:"In Stock", featured:false, badge:null },
  { id:"prod-16", name:"Cold Pressed Tender Coconut Water", category:"beverages", brand:"Pure Tropic", sku:"BEV-COC-016", price:55, originalPrice:65, discount:15, unit:"300 ml Bottle", stock:42, minStock:12, rating:4.8, reviewsCount:95, image:"https://vims.ac.in/vims-hospital/wp-content/uploads/2022/04/Tender-coconut-water-1024x576.jpg", description:"100% pure tender coconut water bottled bio-aseptically without added sugars or preservatives.", tags:["100% Pure","Hydration Boost","Natural Electrolytes"], status:"In Stock", featured:true, badge:"Hydration" },
  { id:"prod-17", name:"Organic Green Tea with Jasmine", category:"beverages", brand:"Simple Truth Organic", sku:"BEV-TEA-017", price:245, originalPrice:310, discount:21, unit:"20 Tea Bags", stock:30, minStock:8, rating:4.7, reviewsCount:78, image:"https://www.kroger.com/product/images/xlarge/front/0001111089106", description:"Delicately scented organic green tea leaves infused with natural fragrant jasmine blossoms.", tags:["Antioxidant","Detox","USDA Organic"], status:"In Stock", featured:false, badge:null },
  { id:"prod-18", name:"Royal Aged Basmati Rice (1121)", category:"rice-grains", brand:"Daawat Heritage", sku:"RCE-BAS-018", price:480, originalPrice:599, discount:20, unit:"5 kg Bag", stock:34, minStock:10, rating:4.9, reviewsCount:260, image:"https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80", description:"2-year aged premium extra-long grain 1121 basmati rice. Non-sticky royal aroma.", tags:["2 Yr Aged","Extra Long Grain"], status:"In Stock", featured:true, badge:"20% OFF" },
  { id:"prod-19", name:"Organic Unpolished Toor Dal", category:"rice-grains", brand:"Tata Sampann", sku:"RCE-DAL-019", price:165, originalPrice:195, discount:15, unit:"500 g", stock:65, minStock:15, rating:4.7, reviewsCount:112, image:"https://www.tatanutrikorner.com/cdn/shop/files/Tata-Sampann-Toor-Arhar-Dal--500g-_FOP_-with-Sanjeev-kapoor_f1f98892-6dbf-40be-822b-a922be48b2b9.png?v=1748858329&width=990", description:"Naturally grown, unpolished yellow pigeon peas (Arhar Dal) with intact dietary fiber and plant protein. Endorsed by Chef Sanjeev Kapoor.", tags:["Unpolished","High Fiber","Rich Protein"], status:"In Stock", featured:false, badge:null },
  { id:"prod-20", name:"Pure Vedic A2 Gir Cow Ghee (Bilona)", category:"cooking-essentials", brand:"Swadeshi VIP", sku:"COK-GHE-020", price:899, originalPrice:1099, discount:18, unit:"500 ml Glass Jar", stock:20, minStock:5, rating:5.0, reviewsCount:184, image:"https://crm.swadeshivip.com/storage/images/uploads/image_20241112_150359.png", description:"Traditional curd-churned Bilona method A2 ghee made from pure grass-fed Gir cow milk. 100% pure Vedic quality in glass jar.", tags:["A2 Bilona","Glass Jar","Vedic Ghee"], status:"In Stock", featured:true, badge:"Super Premium" },
  { id:"prod-21", name:"Cold-Pressed Virgin Mustard Oil", category:"cooking-essentials", brand:"Gramin Pure", sku:"COK-OIL-021", price:195, originalPrice:240, discount:19, unit:"1 Litre Bottle", stock:45, minStock:12, rating:4.8, reviewsCount:93, image:"https://m.media-amazon.com/images/I/71uicmzEajL._SX679_.jpg", description:"Kachi Ghani cold-pressed virgin mustard oil extracted at low temperatures to preserve natural antioxidants and pungent aroma.", tags:["Kachi Ghani","Wood Pressed","Virgin"], status:"In Stock", featured:false, badge:null },
  { id:"prod-22", name:"Organic Kashmiri Saffron (Kesar)", category:"cooking-essentials", brand:"Bharat Vedica", sku:"COK-SAF-022", price:499, originalPrice:650, discount:23, unit:"1 g Sealed Box", stock:15, minStock:4, rating:4.9, reviewsCount:68, image:"https://bharatvedica.com/cdn/shop/files/SAFFRON_01_jpg.jpg?v=1785228310", description:"100% pure Mongra grade Kashmiri saffron threads with deep red coloring power and natural aroma.", tags:["Grade 1 Mongra","100% Pure","Kashmiri Saffron"], status:"In Stock", featured:true, badge:"Exclusive" },
  { id:"prod-23", name:"Crispy Vegetable Samosas (Frozen)", category:"frozen-foods", brand:"Haldiram Express", sku:"FRZ-SAM-023", price:160, originalPrice:190, discount:16, unit:"12 pcs (400 g)", stock:28, minStock:8, rating:4.6, reviewsCount:89, image:"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80", description:"Authentic triangular pastry stuffed with spiced potatoes and peas. Deep fry or air fry in 8 minutes.", tags:["Ready to Fry","Party Snack"], status:"In Stock", featured:false, badge:"Quick Bite" },
  { id:"prod-24", name:"Organic Frozen Green Peas", category:"frozen-foods", brand:"Pro Organic", sku:"FRZ-PEA-024", price:99, originalPrice:130, discount:24, unit:"1 kg Bag", stock:50, minStock:15, rating:4.7, reviewsCount:104, image:"https://cpimg.tistatic.com/08112655/b/4/Pro-Organic-Frozen-Green-Peas-Packaging-Pouch.jpg", description:"Sweet and tender organic green peas individually quick frozen (IQF) within hours of picking to seal in nutrition.", tags:["IQF Technology","Sweet & Juicy","Organic"], status:"In Stock", featured:false, badge:null },
  { id:"prod-25", name:"Organic Neem & Aloe Vera Body Wash", category:"personal-care", brand:"Nimbarka", sku:"PER-BOD-025", price:280, originalPrice:350, discount:20, unit:"300 ml", stock:35, minStock:10, rating:4.8, reviewsCount:71, image:"https://buynimbarka.com/cdn/shop/files/Aloe_Vera_Body_wash_1.jpg?v=1740413991&width=990", description:"Sulphate-free gentle body wash formulated with pure cold-pressed neem seed oil and organic aloe vera extract.", tags:["Sulphate Free","Vegan","Neem & Aloe"], status:"In Stock", featured:false, badge:"20% OFF" },
  { id:"prod-26", name:"Ayurvedic Herbal Toothpaste", category:"personal-care", brand:"Baidyanath", sku:"PER-TPH-026", price:110, originalPrice:130, discount:15, unit:"200 g Tube", stock:48, minStock:12, rating:4.9, reviewsCount:140, image:"https://www.baidyanath.com/cdn/shop/files/WebsiteFront.jpg?v=1771993695&width=1000", description:"Formulated with authentic Ayurvedic herbs, clove and neem for complete cavity protection, gum health, and fresh breath.", tags:["Ayurvedic","Clove & Neem","Enamel Safe"], status:"In Stock", featured:false, badge:null },
  { id:"prod-27", name:"Eco-Friendly Plant Based Floor Cleaner", category:"household", brand:"CleanGreen India", sku:"HOU-CLN-027", price:185, originalPrice:225, discount:18, unit:"1 Litre (Citrus Scent)", stock:29, minStock:8, rating:4.7, reviewsCount:65, image:"https://m.media-amazon.com/images/I/6148G2lRvWL._SX679_.jpg", description:"Non-toxic, pet-safe plant powered liquid cleaner with refreshing natural lemongrass and citrus oils.", tags:["Pet Safe","Plant Based","Eco Friendly"], status:"In Stock", featured:false, badge:null },
  { id:"prod-28", name:"100% Biodegradable Garbage Bags", category:"household", brand:"Ecolastic", sku:"HOU-BAG-028", price:125, originalPrice:150, discount:17, unit:"Pack of 30 (Medium 19x21)", stock:52, minStock:15, rating:4.5, reviewsCount:48, image:"https://www.ecolastic.in/storage/product_images/32411_2025-03-04_12_56_28.jpg", description:"Cornstarch based compostable heavy-duty trash bags with leak-proof bottom sealing.", tags:["Compostable","Leak Proof","100% Biodegradable"], status:"In Stock", featured:false, badge:"Eco Choice" },
  { id:"prod-29", name:"Avocados Hass Imported (Pack of 2)", category:"fruits", brand:"FreshFarm Organics", sku:"FRT-AVO-029", price:269, originalPrice:320, discount:16, unit:"2 pcs (approx 350g)", stock:19, minStock:6, rating:4.8, reviewsCount:84, image:"https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&q=80", description:"Creamy Hass avocados rich in healthy monounsaturated fats and dietary fiber.", tags:["Keto Friendly","Healthy Fats"], status:"In Stock", featured:true, badge:"Trending" },
  { id:"prod-30", name:"Fresh Broccoli Florets", category:"vegetables", brand:"HydroFresh", sku:"VEG-BRO-030", price:89, originalPrice:110, discount:19, unit:"500 g", stock:22, minStock:7, rating:4.6, reviewsCount:51, image:"https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&q=80", description:"Crisp emerald green broccoli crowns loaded with vitamin C and dietary antioxidants.", tags:["Low Calorie","Immunity"], status:"In Stock", featured:false, badge:null },
  { id:"prod-31", name:"Premium Greek Yogurt - Wild Berry", category:"dairy", brand:"Epigamia", sku:"DAI-YOG-031", price:65, originalPrice:75, discount:13, unit:"120 g Cup", stock:31, minStock:10, rating:4.9, reviewsCount:119, image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=600&q=80", description:"Thick, creamy artisanal Greek yogurt infused with real blueberries and raspberries. 2x protein.", tags:["High Protein","Probiotic"], status:"In Stock", featured:false, badge:null },
  { id:"prod-32", name:"Organic Cold Pressed Virgin Olive Oil", category:"cooking-essentials", brand:"Borges Natura", sku:"COK-OLV-032", price:749, originalPrice:899, discount:17, unit:"1 Litre Glass Bottle", stock:16, minStock:5, rating:4.9, reviewsCount:96, image:"https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80", description:"First cold-pressed extra virgin olive oil made from Spanish Picual olives. Zero acidity.", tags:["Extra Virgin","Heart Care"], status:"In Stock", featured:true, badge:"17% OFF" }
];

const INITIAL_CUSTOMERS = [
  { id:"CUST-101", name:"Dileep Kumar", email:"dileep.kumar@example.com", phone:"+91 98490 12345", city:"Tirupati", state:"Andhra Pradesh", ordersCount:8, totalSpent:6420, lastOrderDate:"2026-10-04", status:"Active", avatar:"https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-102", name:"Priya Sharma", email:"priya.sharma@example.com", phone:"+91 98111 23456", city:"Bengaluru", state:"Karnataka", ordersCount:14, totalSpent:12890, lastOrderDate:"2026-10-05", status:"Active", avatar:"https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-103", name:"Rajesh Varma", email:"rajesh.v@example.com", phone:"+91 97000 34567", city:"Hyderabad", state:"Telangana", ordersCount:5, totalSpent:3940, lastOrderDate:"2026-09-28", status:"Active", avatar:"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-104", name:"Sneha Reddy", email:"sneha.reddy@example.com", phone:"+91 99887 45678", city:"Tirupati", state:"Andhra Pradesh", ordersCount:11, totalSpent:9150, lastOrderDate:"2026-10-06", status:"Active", avatar:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-105", name:"Arun Nair", email:"arun.nair@example.com", phone:"+91 94470 56789", city:"Kochi", state:"Kerala", ordersCount:3, totalSpent:2180, lastOrderDate:"2026-09-22", status:"Active", avatar:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-106", name:"Ananya Iyer", email:"ananya.iyer@example.com", phone:"+91 98401 67890", city:"Chennai", state:"Tamil Nadu", ordersCount:9, totalSpent:7850, lastOrderDate:"2026-10-02", status:"Active", avatar:"https://images.unsplash.com/photo-1534751516642-a171ed273f8a?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-107", name:"Vikram Malhotra", email:"vikram.m@example.com", phone:"+91 98200 78901", city:"Mumbai", state:"Maharashtra", ordersCount:6, totalSpent:5200, lastOrderDate:"2026-09-30", status:"Active", avatar:"https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-108", name:"Meera Sen", email:"meera.sen@example.com", phone:"+91 98300 89012", city:"Kolkata", state:"West Bengal", ordersCount:4, totalSpent:3100, lastOrderDate:"2026-09-18", status:"Active", avatar:"https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-109", name:"Karan Johar", email:"karan.j@example.com", phone:"+91 98100 90123", city:"New Delhi", state:"Delhi", ordersCount:2, totalSpent:1450, lastOrderDate:"2026-08-15", status:"Inactive", avatar:"https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80" },
  { id:"CUST-110", name:"Divya Patel", email:"divya.p@example.com", phone:"+91 98790 01234", city:"Ahmedabad", state:"Gujarat", ordersCount:7, totalSpent:5890, lastOrderDate:"2026-10-01", status:"Active", avatar:"https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80" }
];

const INITIAL_ORDERS = [
  { id:"FC-8941", customer:{ name:"Dileep Kumar", phone:"+91 98490 12345", email:"dileep.kumar@example.com", address:"Flat 402, Sri Krishna Heights, Balaji Colony", city:"Tirupati", state:"Andhra Pradesh", pincode:"517501" }, items:[ { productId:"prod-1", name:"Fresh Shimla Red Apples", price:149, quantity:2, unit:"1 kg", image:"https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=200&q=80" }, { productId:"prod-7", name:"Organic Malai Paneer", price:115, quantity:2, unit:"200 g", image:"https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=200&q=80" }, { productId:"prod-20", name:"Pure Vedic A2 Gir Cow Ghee", price:899, quantity:1, unit:"500 ml", image:"https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=200&q=80" } ], subtotal:1427, deliveryFee:0, discount:100, couponCode:"WELCOME100", tax:0, total:1327, paymentMethod:"UPI (Google Pay)", paymentStatus:"Paid", orderStatus:"Out for Delivery", deliverySlot:"Today: 30–60 minutes", deliveryPartner:"Ramesh Reddy (+91 98877 11223)", createdAt:"2026-10-06T10:15:00.000Z", estimatedDelivery:"2026-10-06T11:15:00.000Z", timeline:[ { step:"Order Placed", time:"10:15 AM", done:true }, { step:"Confirmed", time:"10:18 AM", done:true }, { step:"Preparing", time:"10:28 AM", done:true }, { step:"Out for Delivery", time:"10:45 AM", done:true }, { step:"Delivered", time:"Expected 11:15 AM", done:false } ] },
  { id:"FC-8940", customer:{ name:"Sneha Reddy", phone:"+91 99887 45678", email:"sneha.reddy@example.com", address:"House #12-34, Nehru Nagar", city:"Tirupati", state:"Andhra Pradesh", pincode:"517502" }, items:[ { productId:"prod-3", name:"Alphonso Mangoes (Devgad)", price:649, quantity:1, unit:"1 Dozen", image:"https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=200&q=80" }, { productId:"prod-18", name:"Royal Aged Basmati Rice", price:480, quantity:1, unit:"5 kg", image:"https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=200&q=80" } ], subtotal:1129, deliveryFee:0, discount:50, couponCode:"FRESH50", tax:0, total:1079, paymentMethod:"Credit Card (HDFC)", paymentStatus:"Paid", orderStatus:"Preparing", deliverySlot:"Today: 1–2 hours", deliveryPartner:"Siva Kumar", createdAt:"2026-10-06T09:40:00.000Z", estimatedDelivery:"2026-10-06T11:40:00.000Z", timeline:[ { step:"Order Placed", time:"09:40 AM", done:true }, { step:"Confirmed", time:"09:42 AM", done:true }, { step:"Preparing", time:"09:55 AM", done:true }, { step:"Out for Delivery", time:"Pending", done:false }, { step:"Delivered", time:"Pending", done:false } ] },
  { id:"FC-8939", customer:{ name:"Priya Sharma", phone:"+91 98111 23456", email:"priya.sharma@example.com", address:"Villa 108, Palm Meadows, Whitefield", city:"Bengaluru", state:"Karnataka", pincode:"560066" }, items:[ { productId:"prod-14", name:"Roasted California Almonds", price:375, quantity:2, unit:"500 g", image:"https://images.unsplash.com/photo-1508061257971-f7626f220947?auto=format&fit=crop&w=200&q=80" }, { productId:"prod-25", name:"Organic Neem Body Wash", price:280, quantity:1, unit:"300 ml", image:"https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=200&q=80" } ], subtotal:1030, deliveryFee:0, discount:100, couponCode:"WELCOME100", tax:0, total:930, paymentMethod:"UPI (PhonePe)", paymentStatus:"Paid", orderStatus:"Delivered", deliverySlot:"Express 30 Mins", deliveryPartner:"Anil Murthy", createdAt:"2026-10-05T16:20:00.000Z", estimatedDelivery:"2026-10-05T17:00:00.000Z", timeline:[ { step:"Order Placed", time:"04:20 PM", done:true }, { step:"Confirmed", time:"04:22 PM", done:true }, { step:"Preparing", time:"04:30 PM", done:true }, { step:"Out for Delivery", time:"04:42 PM", done:true }, { step:"Delivered", time:"04:58 PM", done:true } ] },
  { id:"FC-8938", customer:{ name:"Rajesh Varma", phone:"+91 97000 34567", email:"rajesh.v@example.com", address:"Flat 2B, Cyber Pearl Apts, Hitech City", city:"Hyderabad", state:"Telangana", pincode:"500081" }, items:[ { productId:"prod-12", name:"Fresh Boneless Chicken", price:249, quantity:2, unit:"500 g", image:"https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=200&q=80" }, { productId:"prod-4", name:"Farm Fresh Hybrid Tomatoes", price:38, quantity:2, unit:"1 kg", image:"https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=200&q=80" } ], subtotal:574, deliveryFee:0, discount:0, couponCode:null, tax:0, total:574, paymentMethod:"Cash on Delivery", paymentStatus:"Paid", orderStatus:"Delivered", deliverySlot:"Today Evening (5-7 PM)", deliveryPartner:"Kiran G", createdAt:"2026-10-04T14:10:00.000Z", estimatedDelivery:"2026-10-04T18:00:00.000Z", timeline:[ { step:"Order Placed", time:"02:10 PM", done:true }, { step:"Confirmed", time:"02:15 PM", done:true }, { step:"Preparing", time:"03:00 PM", done:true }, { step:"Out for Delivery", time:"05:15 PM", done:true }, { step:"Delivered", time:"06:10 PM", done:true } ] },
  { id:"FC-8937", customer:{ name:"Ananya Iyer", phone:"+91 98401 67890", email:"ananya.iyer@example.com", address:"14th Cross, TTK Road, Alwarpet", city:"Chennai", state:"Tamil Nadu", pincode:"600018" }, items:[ { productId:"prod-10", name:"100% Sourdough Bread", price:95, quantity:1, unit:"400 g", image:"https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=200&q=80" }, { productId:"prod-9", name:"Farm Brown Eggs", price:89, quantity:2, unit:"Pack of 6", image:"https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=200&q=80" } ], subtotal:273, deliveryFee:49, discount:0, couponCode:null, tax:0, total:322, paymentMethod:"UPI (Paytm)", paymentStatus:"Paid", orderStatus:"Delivered", deliverySlot:"Morning (7-9 AM)", deliveryPartner:"Bala Murugan", createdAt:"2026-10-02T06:30:00.000Z", estimatedDelivery:"2026-10-02T07:45:00.000Z", timeline:[ { step:"Order Placed", time:"06:30 AM", done:true }, { step:"Confirmed", time:"06:35 AM", done:true }, { step:"Preparing", time:"06:50 AM", done:true }, { step:"Out for Delivery", time:"07:15 AM", done:true }, { step:"Delivered", time:"07:42 AM", done:true } ] }
];

const INITIAL_COUPONS = [
  { code:"WELCOME100", discountType:"flat", discountValue:100, minOrder:699, maxDiscount:100, description:"Get flat ₹100 OFF on your order above ₹699", expiry:"2026-12-31", usageLimit:1000, usedCount:412, status:"Active" },
  { code:"FRESH50", discountType:"flat", discountValue:50, minOrder:499, maxDiscount:50, description:"Save ₹50 on essential groceries above ₹499", expiry:"2026-11-30", usageLimit:500, usedCount:198, status:"Active" },
  { code:"SUPER20", discountType:"percentage", discountValue:20, minOrder:1200, maxDiscount:300, description:"20% OFF on mega basket shopping (up to ₹300)", expiry:"2026-10-31", usageLimit:250, usedCount:84, status:"Active" },
  { code:"VEGGIE15", discountType:"percentage", discountValue:15, minOrder:350, maxDiscount:75, description:"15% OFF on Farm Fresh Fruits & Vegetables", expiry:"2026-12-15", usageLimit:400, usedCount:150, status:"Active" },
  { code:"FREESHIP", discountType:"shipping", discountValue:49, minOrder:299, maxDiscount:49, description:"Free instant delivery on orders above ₹299", expiry:"2026-11-15", usageLimit:800, usedCount:512, status:"Active" }
];

const INITIAL_REVIEWS = [
  { id:"REV-01", customerName:"Dileep Kumar", productName:"Pure Vedic A2 Gir Cow Ghee (Bilona)", productId:"prod-20", rating:5, comment:"The most authentic Bilona ghee I have tasted in years. The aroma fills the entire kitchen!", date:"2026-10-04", status:"Approved" },
  { id:"REV-02", customerName:"Priya Sharma", productName:"Fresh Shimla Red Apples", productId:"prod-1", rating:5, comment:"Crispy, naturally sweet, and well packaged. Delivered in less than 35 minutes!", date:"2026-10-05", status:"Approved" },
  { id:"REV-03", customerName:"Sneha Reddy", productName:"Alphonso Mangoes (Devgad)", productId:"prod-3", rating:5, comment:"Devgad Alphonso delivered in perfect condition. Every single mango was pulpy and aromatic.", date:"2026-10-03", status:"Approved" },
  { id:"REV-04", customerName:"Rajesh Varma", productName:"Fresh Boneless Chicken Breast", productId:"prod-12", rating:5, comment:"Clean cut, completely odorless and very fresh. Made chicken tikka and it remained juicy.", date:"2026-10-02", status:"Approved" },
  { id:"REV-05", customerName:"Ananya Iyer", productName:"Organic Malai Paneer", productId:"prod-7", rating:5, comment:"Soft like a cloud! Dissolved smoothly in palak paneer.", date:"2026-10-01", status:"Approved" },
  { id:"REV-06", customerName:"Divya Patel", productName:"Organic Kashmiri Saffron (Kesar)", productId:"prod-22", rating:5, comment:"Genuine Mongra saffron. Just 2 threads turned warm milk into a rich golden yellow.", date:"2026-09-29", status:"Approved" },
  { id:"REV-07", customerName:"Vikram Malhotra", productName:"Roasted California Almonds", productId:"prod-14", rating:4, comment:"Very fresh and perfectly roasted. Lightly salted, not overwhelming.", date:"2026-09-28", status:"Approved" },
  { id:"REV-08", customerName:"Arun Nair", productName:"Fresh Sea Prawns", productId:"prod-13", rating:5, comment:"Properly deveined and very fresh catch. Fried them with Kerala spices.", date:"2026-09-22", status:"Approved" },
  { id:"REV-09", customerName:"Meera Sen", productName:"100% Whole Wheat Sourdough Bread", productId:"prod-10", rating:4, comment:"Delicious crust and airy crumb. Great with salted butter and poached eggs.", date:"2026-09-18", status:"Approved" },
  { id:"REV-10", customerName:"Karan Johar", productName:"Cold Pressed Tender Coconut Water", productId:"prod-16", rating:4, comment:"Tastes just like freshly opened coconut. No weird artificial aftertaste.", date:"2026-08-16", status:"Approved" }
];

const STORE_SETTINGS = {
  storeName:"FreshCart Grocery",
  tagline:"Fresh groceries, delivered to your doorstep.",
  phone:"+91 1800-419-3322",
  email:"support@freshcart.in",
  address:"FreshCart Central Hub, Industrial Estate, Tirupati, AP - 517501",
  currency:"₹",
  freeDeliveryThreshold:499,
  defaultDeliveryFee:49,
  enableCOD:true,
  enableUPI:true,
  enableCards:true,
  enableNetBanking:true,
  deliverySlots:[ "30–60 minutes (Express Delivery)", "1–2 hours (Fast Delivery)", "Today Evening (5:00 PM – 7:30 PM)", "Tomorrow Morning (7:00 AM – 9:30 AM)" ]
};
